[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 115200
upload_flags = --no-stub
build_unflags = 
    -std=gnu++11
build_flags = 
    -std=gnu++17
    -Wall
board_build.partitions = huge_app.csv
lib_deps =
    lovyan03/LovyanGFX
    tzapu/WiFiManager
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    bblanchon/ArduinoJson